# Generated by Django 3.0.5 on 2020-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
