# Generated by Django 3.0.5 on 2020-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_comment_is_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
